create or replace view v_alarmdefinenew as
select a.id ,
a.catalog ,(select xtxx from xtbm xt1 where a.catalog=xt1.xtbm) catalogname,
a.vendor,
(select xtxx from xtbm xt2 where a.vendor=xt2.xtbm) vendorname,
a.o_Alarmdesc,
a.o_alarmlevel,
(select al.level_name from alarm_level al where a.o_alarmlevel=al.endesc) o_alarmlevelname,
a.n_alarmdesc,
a.n_alarmlevel,
(select al.level_name from alarm_level al where a.n_alarmlevel=al.endesc) n_alarmlevelname,
a.alarmdetail,
a.isfilter,
decode(a.isfilter,
              0,
              '不过滤',
              1,
              '屏蔽显示',
              -1,
              '直接不入库'
              ) isfilterdesc,
a.remark,
a.updateperson,
a.updatedate ,
a.iscansend,
decode(a.iscansend,
              0,
              '非根告警',
              1,
              '可能根告警',
              2,
              '肯定是根告警'
              ) iscansenddesc,
a.topoalarm,
decode(a.topoalarm,
              0,
              '非光路告警',
              1,
              '可能光路告警',
              2,
              '肯定是光路告警'
              ) topoalarmdesc,
a.noalarm
  from  alarmdefine a;

